version: '2'
services:
  loadbalancer:
    start_on_create: true
    scale: 1
    lb_config:
      port_rules:
      - source_port: 8090
        target_port: 5000
        service: web
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  web:
    scale: 2
  redis:
    scale: 1
